apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jpem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jpem
    app.kubernetes.io/part-of: byoc-app-kzsy
  name: jpem
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: jpem
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: jpem
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-egiu-tenant/byoc-app-kzsy/jpem@sha256:d22e476c72d6f494159f03fe7207736929bb099fe58acb9ab1fd89dcf221384d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
