apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jpem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jpem
    app.kubernetes.io/part-of: byoc-app-kzsy
  name: jpem
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: jpem
status:
  loadBalancer: {}
