apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jpem
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-egiu-tenant/byoc-app-kzsy/jpem@sha256:d22e476c72d6f494159f03fe7207736929bb099fe58acb9ab1fd89dcf221384d
        name: my-java-quarkus
        resources: {}
status: {}
