apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jpem
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jpem
    app.kubernetes.io/part-of: byoc-app-kzsy
  name: jpem
spec:
  rules:
  - host: jpem-byoc-egiu-tenant.apps.bbc43ee588ebb150cfcf.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: jpem
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
